### ISSUE TITLE
how to use a Communities model from civitai or huggingface

### ISSUE THREAD

**Issue by AhBumm** [ttchengab/zest_code#4]
the model from huggingface, /unet/model.safetensors can't load.
run demo_gradio.py logs:
```
Traceback (most recent call last):
  File "E:\zest_code\demo_gradio.py", line 37, in <module>
    pipe = StableDiffusionXLControlNetInpaintPipeline.from_pretrained(
  File "E:\zest_code\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\zest_code\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 819, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "E:\zest_code\venv\lib\site-packages\diffusers\pipelines\pipeline_loading_utils.py", line 473, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "E:\zest_code\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\zest_code\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 632, in from_pretrained
    model_file = _get_model_file(
  File "E:\zest_code\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\zest_code\venv\lib\site-packages\diffusers\utils\hub_utils.py", line 306, in _get_model_file
    raise EnvironmentError(
OSError: Error no file named diffusion_pytorch_model.bin found in directory ./Juggernaut-XL-v9\unet.
```

**Comment by ttchengab** [comment]
Hi @AhBumm, which version of diffusers are you using?

**Comment by AhBumm** [comment]
> Hi @AhBumm, which version of diffusers are you using?

My diffusers is diffusers==0.27.2
